drop table if exists books CASCADE ;
drop table if exists borrow CASCADE ;


drop table if exists users CASCADE ;
drop sequence if exists library_sequence;
create sequence library_sequence start with 1 increment by 1;


    create table books (
       id integer not null generated by default as identity,
        author varchar(255),
        isbn_no varchar(255),
        name varchar(255),
        publication varchar(255),
        quantity integer,
        year_of_publication varchar(255),
        primary key (id)
    );


    create table borrow (
       id integer generated by default as identity,
        is_returned integer,
        library_card_number varchar(255),
        book_id integer,
        user_id integer,
        primary key (id)
    );


    create table users (
       id integer not null generated by default as identity,
        address varchar(255),
        is_active integer,
        library_card_number varchar(255),
        name varchar(255),
        primary key (id)
    );


    alter table borrow
       add constraint FKtrw1lxelfcyso4uenvk1wy9q5
       foreign key (book_id)
       references books;


    alter table borrow
       add constraint FKrby7un94muby8qxwumbkioiu9
       foreign key (user_id)
       references users;